### ISSUE TITLE
Update to new @use Syntax in Angular Material

### ISSUE THREAD

**Issue by SvenBudak** [Artik-Man/material-theme-creator#10]
@Artik-Man Hello and thank you very much for this outstanding and helpful pur css solution! But unfortunately it doesn't work with the new @use syntax that the Angular Material team has implemented. Are you planning an update for this package?

https://material.angular.io/guide/theming

**Comment by Artik-Man** [comment]
Hello, Sven. At the time I'm not planning to update the library, but maybe i will do it in 1-3 months. If you can help me with it, i will be happy)

**Comment by Artik-Man** [comment]
@SvenBudak 

Ok. I found the solution. 


[https://github.com/Artik-Man/material-theme-creator-demo-page/blob/master/src/styles.scss](https://github.com/Artik-Man/material-theme-creator-demo-page/blob/master/src/styles.scss)

v. 3.1.1

```
@use '~@angular/material' as mat;
@use "~material-theme-creator/ngx-mtc" as ngx-mtc;

@import '~@angular/material/theming';


@include mat.core();
@include ngx-mtc.init();

$primary-map: ngx-mtc.create-theme-map('primary');
$primary-palette: mat.define-palette($primary-map);

$accent-palette: mat.define-palette(mat.$grey-palette, A200, A100, A400);

$warn-palette: mat.define-palette(mat.$red-palette);

$theme: ngx-mtc.custom-theme(
    $primary-palette,
    $accent-palette,
    $warn-palette,
);


@include mat.all-component-themes($theme);

@media (prefers-color-scheme: dark) {
  :root {
    --is-dark-theme: 1;
  }
}

@media (prefers-color-scheme: light) {
  :root {
    --is-dark-theme: 0;
  }
}

:root {
  @include ngx-mtc.theme-base(); 
  @include ngx-mtc.create-variables-from-color('primary', #3f51b5, 50%);
}


```
