### ISSUE TITLE
Angular 13 - ~@angular/material issues import css

### ISSUE THREAD

**Issue by manuel-mods** [Artik-Man/material-theme-creator#19]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `material-theme-creator@3.2.0` for the project I'm working on.

~@angular/material issues in css with angular 13.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/material-theme-creator/ngx-mtc.scss b/node_modules/material-theme-creator/ngx-mtc.scss
index da9b238..7f47cdc 100644
--- a/node_modules/material-theme-creator/ngx-mtc.scss
+++ b/node_modules/material-theme-creator/ngx-mtc.scss
@@ -1,5 +1,5 @@
 @use "core" as mtc;
-@use '~@angular/material' as mat;
+@use '@angular/material' as mat;
 
 /// @deprecated
 @mixin ngx-mtc-init() {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by SvenBudak** [comment]
This is a very simple fix. please apply it :)

**Comment by randysimplist** [comment]
Can we please merge this change? This is preventing us from updating our Material version.

**Comment by Artik-Man** [comment]
I'm sorry for my loooong answer. 
@manuel-mods @SvenBudak @randysimplist 

https://github.com/Artik-Man/material-theme-creator/commit/889235f0be414712a2eff9a8ec3b8beb47fb1604
