### ISSUE TITLE
How to change theme dynamically

### ISSUE THREAD

**Issue by mhosman** [Artik-Man/material-theme-creator#8]
Great library! I wanted to know if there's a way to change the theme dynamically taking an hex primary color from javascript.
Thanks!

**Comment by SvenBudak** [comment]
@mhosman You have in `:root` 3 variables:

```
--my-theme-h: 220;
--my-theme-s: 80;
--my-theme-l: 60;
```

Just google a bit and you will understand how you can manipulate this css varaibles with javascript ;)

For example: `document.documentElement.style.setProperty('--my-theme-h', '123');` will change the first var on the html tag.

**Comment by Artik-Man** [comment]
1. convert your HEX primary color to HSL variables (`#FF0000` -> `0, 100, 50`) 
[https://css-tricks.com/converting-color-spaces-in-javascript/#hex-to-hsl](https://css-tricks.com/converting-color-spaces-in-javascript/#hex-to-hsl)

2. update `--your-theme-` H, S and L variables with current color-components
```
document.documentElement.style.setProperty('--your-theme-h', '0');
document.documentElement.style.setProperty('--your-theme-s', '100');
document.documentElement.style.setProperty('--your-theme-l', '50');
```
